CHATBOT/backend/backend/urls.py
from django.urls import include, path
from rest_framework import routers
from backend.api import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
#router.register(r'diagnoses', views.DiagnosisViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path(r'similar-symptoms', views.SimilarSymptoms.as_view(), name="similar-symptoms"),
    path(r'diagnoses', views.Diagnosis.as_view(), name="diagnosis"),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

mainapp/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.loginUser, name="loginuser"),
    path('signup/', views.RegUser, name="reguser"),
    url(r'^external', views.external),
    url(r'^chatbot', views.chatbot),
    path('signup/complete', views.completeaccount, name="completeaccount"),
    path('users/edit/', views.UpdateUser, name="updateuser"),
    path('user/dashboard/', views.dash, name="dashboard"),
    path('logout/', views.logout_view, name="logout"),
    path('user/account/', views.account, name="account"),
    path('user/notification/', views.notif, name="notification"),
    path('user/reports/', views.viewreport, name='report'),
    path('user/email/', views.mail, name='mail'),
    path('user/reports/<int:pk>', views.viewreportdetail, name='reportdetail'),
]

medeasy/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls')),
    path('user/predictions/',include('predict.urls')),
    path('user/edit/',include('mainapp.urls'))
]

predict/urls.py
from django.urls import path
from . import views

import numpy as np
from flask import Flask, request, jsonify, render_template
import pickle

app_name='predict'

urlpatterns=[
	path('predict/', views.predict, name="predicter"),
	path('predict/save',views.saveresults,name="saveresult")
]

mainapp/models.py
from django.db import models
from users.models import CustomUser
import datetime


class Doctor(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=50, blank=False)
    lastname = models.CharField(max_length=50, blank=False)
    phonenumber = models.CharField(max_length=10, blank=False)
    degrees = models.CharField(max_length=50, blank=False)
    iscertified = models.BooleanField(default=False)
    registrationno = models.CharField(max_length=30)
    bio = models.CharField(max_length=100)
    numberofpatients = models.IntegerField(default=0, blank=True)

    def __str__(self):
        return self.user.username


class Patient(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    firstname = models.CharField(max_length=50, blank=False)
    lastname = models.CharField(max_length=50, blank=False)
    dateofbirth = models.CharField(max_length=10, blank=False)
    address = models.CharField(max_length=100, default=None, blank=True)
    phonenumber = models.CharField(max_length=10, default=None, blank=True)
    age = models.IntegerField()
    sex = models.CharField(max_length=6, blank=False)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.user.username


class ModelReport(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    report_content = models.CharField(max_length=500)

    def __str__(self):
        return self.patient.user.username


class ModelTwoReport(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    report_content = models.CharField(max_length=500)

    def __str__(self):
        return self.patient.user.username


class Notifications(models.Model):
    patient = models.ForeignKey(Patient, on_delete=models.CASCADE)
    doctor = models.ForeignKey(Doctor, on_delete=models.CASCADE)
    hasNotification = models.BooleanField(default=False)
    msg = models.CharField(max_length=400)

    def __str__(self):
        return self.patient.user.username + '    '+self.doctor.user.username

mainapp/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import authenticate, login, logout
from users.models import CustomUser
import datetime as dt
from .models import Patient, Doctor, Notifications,ModelReport
from django.core.mail import EmailMessage
from django.shortcuts import redirect
import requests
import sys
from subprocess import run,PIPE


def getmatchingdoctor():
    doctors = Doctor.objects.all().order_by('numberofpatients')
    doctor_to_return = doctors[0]
    doctor_to_return.numberofpatients += 1
    doctor_to_return.save()
    return doctor_to_return


def logout_view(request):
    logout(request)
    return HttpResponseRedirect(reverse('mainapp:index'))


def index(request):
    return render(request, 'mainapp/HomePage.html')


def loginUser(request):
    context = {'error': 'Wrong Username or Password'}
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            login(request, user)
            return HttpResponseRedirect(reverse('mainapp:dashboard'))
        else:
            return render(request, 'mainapp/login.html', context)
    else:
        return render(request, 'mainapp/login.html')


# Add the radio button to get the type of user in both the html and the func below

def RegUser(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        email = request.POST.get('email')
        password = request.POST.get('password')
        usertype = request.POST.get('usertype')
        try:
            new_user = CustomUser.objects.create_user(username=username, email=email, password=password,
                                                      user_type=usertype)
            login(request, new_user)
            return HttpResponseRedirect(reverse('mainapp:completeaccount'))
        except:
            return render(request, 'mainapp/signup.html', {'isfail': True})
    else:
        return render(request, 'mainapp/signup.html', {'isfail': False})


@login_required
def completeaccount(request):
    if request.method == 'GET':
        if request.user.user_type == 'Patient':
            return render(request, 'mainapp/patientcompleteaccount.html')
        elif request.user.user_type == 'Doctor':
            return render(request, 'mainapp/doctorcompleteaccount.html')
        else:
            return HttpResponseRedirect(reverse('mainapp:reguser'))

    elif request.method == 'POST':
        if request.user.user_type == 'Patient':
            firstname = request.POST.get('firstname')
            lastname = request.POST.get('lastname')
            address = request.POST.get('address', default=None)
            phonenumber = request.POST.get('phonenumber', default=None)
            dateofbirth = request.POST.get('dateofbirth')
            age = dt.datetime.now().year - int(dateofbirth[0:4])
            sex = request.POST.get('sex')
            user = request.user
            patient_obj = Patient(user=user, firstname=firstname, lastname=lastname, dateofbirth=dateofbirth,
                                  address=address, phonenumber=phonenumber, age=age, sex=sex)
            if patient_obj:
                patient_obj.doctor = getmatchingdoctor()
                em=patient_obj.doctor.user.email
                body="{} is now your patient! ".format(patient_obj.user.username)
                mel=EmailMessage("New Patient",body,to=[em])
                mel.send()
                patient_obj.save()
                return HttpResponseRedirect(reverse('mainapp:dashboard'))
            else:
                return HttpResponseRedirect(reverse('mainapp:reguser'))

        elif request.user.user_type == 'Doctor':
            firstname = request.POST.get('firstname')
            lastname = request.POST.get('lastname')
            phonenumber = request.POST.get('phonenumber', default=None)
            user = request.user
            degrees = request.POST.get('degrees')
            registrationno = request.POST.get('registrationno')
            bio = request.POST.get('bio')
            doctor_obj = Doctor(user=user, firstname=firstname, lastname=lastname, phonenumber=phonenumber,
                                degrees=degrees, registrationno=registrationno, bio=bio)
            if doctor_obj:
                doctor_obj.save()
                return HttpResponseRedirect(reverse('mainapp:dashboard'))
            else:
                return HttpResponseRedirect(reverse('mainapp:reguser'))
    else:
        return HttpResponseRedirect(reverse('mainapp:reguser'))


def external(request):
    inp= request.POST.get('param')
    out= run([sys.executable,'C:\\Users\\Jayit\\Downloads\\MEDHEART-master\\medeasy\\clean_code.py'],shell=True,stdout=PIPE)
    print(out)
    return render(request,'mainapp/HomePage.html',{'data1':out.stdout})

def chatbot(request):
    inp= request.POST.get('param')
    out= run([sys.executable,'C:\\Users\\Jayit\\Downloads\\MEDHEART-master\\medeasy\\Medical-Chatbot-master\\QuestionDiagonosisTkinter.py'],shell=True,stdout=PIPE)
    print(out)
    return render(request,'mainapp/HomePage.html',{'data2':out.stdout})


@login_required
def UpdateUser(request):
    if request.method == 'POST':
        if request.user.user_type == 'Doctor':
            user = request.user
            firstname = request.POST.get('firstname')
            lastname = request.POST.get('lastname')
            phonenumber = request.POST.get('phone')
            degrees = request.POST.get('degrees')
            iscert = request.POST.get('certification')
            regno = request.POST.get('regno')
            bio = request.POST.get('bio')
            doc = Doctor.objects.get(user=request.user)
            doc.user = user
            doc.firstname = firstname
            doc.lastname = lastname
            doc.phonenumber = phonenumber
            doc.degrees = degrees
            if iscert == 'YES':
                iscert = True
            else:
                iscert = False
            doc.iscertified = iscert
            doc.registrationno = regno
            doc.bio = bio
            doc.save()
            return HttpResponseRedirect(reverse('mainapp:dashboard'))
        elif request.user.user_type == 'Patient':
            user = request.user
            firstname = request.POST.get('firstname')
            lastname = request.POST.get('lastname')
            dob = request.POST.get('dob')
            address = request.POST.get('addr')
            sex = request.POST.get('sex')
            phonenumber = request.POST.get('phone')
            pat = Patient.objects.get(user=user)
            pat.user = user
            pat.firstname = firstname
            pat.lastname = lastname
            pat.phonenumber = phonenumber
            pat.dateofbirth = dob
            pat.age = dt.datetime.now().year - int(dob[0:4])
            pat.address = address
            pat.sex = sex
            pat.save()
            return HttpResponseRedirect(reverse('mainapp:dashboard'))
    if request.method == 'GET':
        if request.user.user_type == 'Doctor':
            docdata = Doctor.objects.get(user=request.user)
            return render(request, 'mainapp/doctorUpdate.html', {'data': docdata})
        elif request.user.user_type == 'Patient':
            user = request.user
            patdata = Patient.objects.get(user=user)
            return render(request, 'mainapp/patientUpdate.html', {'data': patdata})
    else:
        return HttpResponseRedirect(reverse('mainapp:reguser'))


@login_required
def dash(request):
    context = {'usertype': request.user.username}
    if request.user.user_type == 'Patient':
        return render(request, 'mainapp/Dashboard.html', {'usertype': request.user.username})
    elif request.user.user_type == 'Doctor':
        doc = Doctor.objects.get(user=request.user)
        docNotif = Notifications.objects.filter(doctor=doc)
        docNotif = docNotif.filter(hasNotification=True)
        if docNotif:
            context['notif'] = 'You have new notifications'
        return render(request, 'mainapp/DashboardTwo.html', context)
    else:
        return HttpResponseRedirect(reverse('mainapp:reguser'))


@login_required
def account(request):
    if request.user.user_type == 'Doctor':
        doc = Doctor.objects.get(user=request.user)
        return render(request, 'mainapp/detailDoctor.html', {'data': doc})
    elif request.user.user_type == 'Patient':
        pat = Patient.objects.get(user=request.user)
        return render(request, 'mainapp/detailPatient.html', {'data': pat})
    else:
        return HttpResponseRedirect(reverse('mainapp:reguser'))


@login_required
def notif(request):
    if request.user.user_type != 'Doctor':
        return HttpResponseRedirect(reverse('mainapp:userlogin'))
    else:
        doc = Doctor.objects.get(user=request.user)
        docNotif = Notifications.objects.filter(doctor=doc)
        res = []
        for notif in docNotif:
            notif.hasNotification = False
            res.append(notif.patient.user.username)
            notif.save()
        k = list(set(res))
    print(k)
    return render(request, 'mainapp/Notification.html', {'k': k})

def mail(request):
    if request.method == 'POST':
        if request.user.user_type == 'Patient':
            pat = Patient.objects.get(user=request.user)
            docEmail = pat.doctor.user.email
            body = request.POST.get('body')
            email = EmailMessage('Medical Report', body, to=[docEmail])
            email.send()
            return HttpResponseRedirect(reverse('mainapp:dashboard'))
        if request.user.user_type == 'Doctor':
            doc = Doctor.objects.get(user=request.user)
            patEmail = request.POST.get('emailauth')

mainapp/templates/mainapp/Dashboard.html
<html>
{% load static %}
    <head>
    <link rel="stylesheet" type="text/css" href="{% static 'mainapp/Dashboard.css' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link href="https://fonts.googleapis.com/css?family=Cantarell&display=swap" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Anton|Roboto&display=swap" rel="stylesheet">
    </head>
    
    <body bgcolor = "white">
        <div class="sidenav">
        <div class="MainLogo"><img style="height:120px;width:120px;margin-left:30px;margin-bottom:5px;border-radius:50%;" src="{% static 'mainapp/logo.png' %}"></div>
        <!-- <a href="{% url 'mainapp:account' %}">Profile</a> -->
        <a href="{% url 'predict:predicter' %}">Self Diagnosis Check</a>
        <!-- <a href="{% url 'mainapp:report' %}">View Reports</a> -->
        <a href="{% url 'mainapp:mail' %}">Send Email</a>
        <!-- <a href="{% url 'mainapp:updateuser' %}">Update Details</a> -->
        <a href="{% url 'mainapp:logout' %}">Logout</a>
        </div>

        <!-- Page content -->
        <div class="main">
            <p style="font-family:Roboto">Welcome {{ usertype }}</p>
            <!-- <img style="height:500px;width:900px;padding-top:50px;" src="{% static 'mainapp/sign_up_page.png' %}"> -->
            <img style="height:500px;width:900px;border-radius:5%;margin-top:25px;margin-left:25px;" src="https://www.bhf.org.uk/-/media/upload/facebook-share-image_v5-1.png">
        </div>
    </body>
    
    
</html>

mainapp/templates/mainapp/DoctorEmail.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'mainapp/login.css' %}">
  <title>MedEasy</title>

</head>

<body class="align">

  <div class="sidenav">
  <img style="height:200px;width:200px;" src="{% static 'mainapp/logo.png' %}">
  
  <a href="{% url 'mainapp:account' %}">Profile</a>
  <a href="{% url 'mainapp:report' %}">View Reports</a>
  <a href="{% url 'mainapp:updateuser' %}">Update Details</a>
      {%  if notif %}
      <a href="{% url 'mainapp:notification' %}">New Notifications</a>
      {% endif %}
  <a href="{% url 'mainapp:mail' %}">Send Email</a>
  <a href="{% url 'mainapp:logout' %}">Logout</a>
  </div>

  <div class="grid">
    <form method="POST" class="form login">
        {% csrf_token %}

      <div class="form__field">
            <label for="login__username"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#user"></use></svg><span class="hidden">Firstname</span></label>
        <input id="login__username" list = 'emailauth'  type="text" name="emailauth" class="form__input" placeholder="Enter the Email Address" required>
          <datalist id = emailauth>
              {% for i in patients %}
                <option value="{{ i.user.email }}"></option>
              {% endfor %}
          </datalist>
      </div>

        <div class="form__field">
        <label for="login__username"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#user"></use></svg><span class="hidden">Firstname</span></label>
        <input id="login__username" type="text" name="body" class="form__input" placeholder="Enter the body" required>
      </div>

      <div class="form__field">
        <input type="submit" value="Send">
      </div>

    </form>

  </div>

  <svg xmlns="http://www.w3.org/2000/svg" class="icons"><symbol id="arrow-right" viewBox="0 0 1792 1792"><path d="M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z"/></symbol><symbol id="lock" viewBox="0 0 1792 1792"><path d="M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z"/></symbol><symbol id="user" viewBox="0 0 1792 1792"><path d="M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z"/></symbol></svg>

</body>

<script type="text/javascript">
  if({{ iffail }} == True)
    alert("Failed to create user");
</script>

</html>

mainapp/templates/mainapp/Notification.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'mainapp/login.css' %}">
  <title>MedEasy</title>

</head>

<body class="align">

  <div class="sidenav">
  <img style="height:200px;width:200px;" src="{% static 'mainapp/logo.png' %}">
  
  <!-- <a href="{% url 'mainapp:account' %}">Profile</a> -->
  <!-- <a href="{% url 'mainapp:report' %}">View Reports</a> -->
  <!-- <a href="{% url 'mainapp:updateuser' %}">Update Details</a> -->
      {%  if notif %}
      <a href="{% url 'mainapp:notification' %}">New Notifications</a>
      {% endif %}
  <a href="{% url 'mainapp:mail' %}">Send Email</a>
  <a href="{% url 'mainapp:logout' %}">Logout</a>
  </div>

  <div class="grid">
    <form method="POST" class="form login">
        {% csrf_token %}
        {% for name in k %}
          <h1 class = "error">Notifications</h1>
                <div class="form__field">
            <label for="login__username"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#user"></use></svg><span class="hidden">Username</span></label>
            <input id="login__username" readonly="readonly" type="text" name="firstname" class="form__input" placeholder="First Name" value="{{name}} has performed a Prediction Check">
          </div>
        {%  endfor %}

    </form>

  </div>

  <svg xmlns="http://www.w3.org/2000/svg" class="icons"><symbol id="arrow-right" viewBox="0 0 1792 1792"><path d="M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z"/></symbol><symbol id="lock" viewBox="0 0 1792 1792"><path d="M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z"/></symbol><symbol id="user" viewBox="0 0 1792 1792"><path d="M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z"/></symbol></svg>

</body>

<script type="text/javascript">
  if({{ iffail }} == True)
    alert("Failed to create user");
</script>

</html>

mainapp/templates/mainapp/PatientEmail.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'mainapp/login.css' %}">
  <title>MedEasy</title>

</head>

<body class="align">

  <div class="sidenav">
      <img style="height:200px;width:200px;" src="{% static 'mainapp/logo.png' %}">

  <!-- <a href="{% url 'mainapp:account' %}">Profile</a> -->
  <a href="{% url 'predict:predicter' %}">Self Diagnosis Check</a>
  <!-- <a href="{% url 'mainapp:report' %}">View Reports</a> -->
      <a href="{% url 'mainapp:mail' %}">Send Email</a>
      <!-- <a href="{% url 'mainapp:updateuser' %}">Update Details</a> -->
      <a href="{% url 'mainapp:logout' %}">Logout</a>
  </div>

  <div class="grid">
    <h1 style="text-align: center;">Send a message to your doctor</h1>
    <br>
    <form method="POST" class="form login">
        {% csrf_token %}

      <div class="form__field">
        <label for="login__username"><svg class="icon"><use xmlns:xlink="http://www.w3.org/1999/xlink" xlink:href="#user"></use></svg><span class="hidden">Firstname</span></label>
        <input id="login__username" type="text" name="body" class="form__input" placeholder="Enter the body" required>
      </div>

      <div class="form__field">
        <input type="submit" value="Send">
      </div>

    </form>

  </div>

  <svg xmlns="http://www.w3.org/2000/svg" class="icons"><symbol id="arrow-right" viewBox="0 0 1792 1792"><path d="M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z"/></symbol><symbol id="lock" viewBox="0 0 1792 1792"><path d="M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z"/></symbol><symbol id="user" viewBox="0 0 1792 1792"><path d="M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z"/></symbol></svg>

</body>

<script type="text/javascript">
  if({{ iffail }} == True)
    alert("Failed to create user");
</script>

</html>

mainapp/templates/mainapp/doctorreportlist.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
	<title>Reports</title>
	<link rel="stylesheet" href="{% static 'mainapp/login.css' %}">
	<style type="text/css">
		.box{
			background-color: #454a46;
			height: 500px;
			width: 500px;
			overflow-y: scroll;
			text-align: center;
			padding: 10px;
		}
		.wrap{
			background-color: #7a7d7b;
			width:60%;
			margin-left: 20%;
			margin-right:20%;
			border-radius: 4px;
		}
		.link{
			width: 100%;
			font-family: Cantarell;
			font-size:30px;
		}
	</style>
</head>
<body class="align">

	<div class="sidenav">
	<img style="height:200px;width:200px;" src="{% static 'mainapp/logo.png' %}">
	
	<a href="{% url 'mainapp:account' %}">Profile</a>
	<a href="{% url 'mainapp:report' %}">View Reports</a>
	<a href="{% url 'mainapp:updateuser' %}">Update Details</a>
	    {%  if notif %}
	    <a href="{% url 'mainapp:notification' %}">New Notifications</a>
	    {% endif %}
	<a href="{% url 'mainapp:mail' %}">Send Email</a>
	<a href="{% url 'mainapp:logout' %}">Logout</a>
	</div>

	<div class="box">
	{% for object in objectlist %}
		<div class="wrap" style="font-family: Cantarell">
			<a class="link" href="{% url 'mainapp:report' %}{{object.id}}">{{object.patient.user.username}} Report {{forloop.counter}}</a>
			<br>
		</div>
	{% endfor %}
	</div>

</body>
</html>