CHATBOT/backend/backend/urls.py
from django.urls import include, path
from rest_framework import routers
from backend.api import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)
#router.register(r'diagnoses', views.DiagnosisViewSet)

# Wire up our API using automatic URL routing.
# Additionally, we include login URLs for the browsable API.
urlpatterns = [
    path('', include(router.urls)),
    path(r'similar-symptoms', views.SimilarSymptoms.as_view(), name="similar-symptoms"),
    path(r'diagnoses', views.Diagnosis.as_view(), name="diagnosis"),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework'))
]

mainapp/urls.py
from django.urls import path
from . import views
from django.conf.urls import url

app_name = 'mainapp'

urlpatterns = [
    path('', views.index, name="index"),
    path('login/', views.loginUser, name="loginuser"),
    path('signup/', views.RegUser, name="reguser"),
    url(r'^external', views.external),
    url(r'^chatbot', views.chatbot),
    path('signup/complete', views.completeaccount, name="completeaccount"),
    path('users/edit/', views.UpdateUser, name="updateuser"),
    path('user/dashboard/', views.dash, name="dashboard"),
    path('logout/', views.logout_view, name="logout"),
    path('user/account/', views.account, name="account"),
    path('user/notification/', views.notif, name="notification"),
    path('user/reports/', views.viewreport, name='report'),
    path('user/email/', views.mail, name='mail'),
    path('user/reports/<int:pk>', views.viewreportdetail, name='reportdetail'),
]

medeasy/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('mainapp.urls')),
    path('user/predictions/',include('predict.urls')),
    path('user/edit/',include('mainapp.urls'))
]

predict/urls.py
from django.urls import path
from . import views

import numpy as np
from flask import Flask, request, jsonify, render_template
import pickle

app_name='predict'

urlpatterns=[
	path('predict/', views.predict, name="predicter"),
	path('predict/save',views.saveresults,name="saveresult")
]

predict/models.py
from django.db import models

# Create your models here.

predict/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from mainapp.models import ModelReport,Patient, Notifications, Doctor
import numpy as np
import pickle
from django.core.mail import EmailMessage
import os
from django.urls import reverse

# Create your views here.

@login_required
def predict(request):
	if request.method == 'GET':
		if request.user.user_type == 'Patient':
			return render(request,'predict/index.html')
		else:
			# return HttpResponseRedirect(reverse('mainapp:reguser'))
			return HttpResponseRedirect(reverse('mainapp:loginuser'))
	if request.method == 'POST':
		if request.user.user_type == 'Patient':
			with open('predict/model.pkl','rb') as model_pkl:
				model = pickle.load(model_pkl)
				request_values=request.POST
				request_values=request_values.dict()
				del request_values['csrfmiddlewaretoken']
				int_features = [int(x) for x in request_values.values()]
				final_features = [np.array(int_features)]
				final_features=np.int64(final_features)
				prediction = model.predict(final_features)
				output = round(prediction[0], 2)
				if(output == 1):
					message="You might have a condition, consult a doctor"
					pat = Patient.objects.get(user=request.user)
					docEmail = pat.doctor.user.email
					body = "The prediction showed a positive result for a heart condition in one of your patient. Please check on them immediately."
					email = EmailMessage('Medical Emergency', body, to=[docEmail])
					email.send()
				else:
					message="Your heart is healthy"
				return render(request,'predict/results.html',{'output':message,'params':request_values})
		else:
			# return HttpResponseRedirect(reverse('mainapp:reguser'))
			return HttpResponseRedirect(reverse('mainapp:loginuser'))

@login_required
def saveresults(request):
	if request.method == 'POST':
		if request.user.user_type == 'Patient':
			request_values=request.POST
			request_values=dict(request_values)
			del request_values['csrfmiddlewaretoken']
			curr_patient=Patient.objects.get(user=request.user)
			model_obj=ModelReport(patient=curr_patient,report_content=str(request_values))
			if model_obj:
				model_obj.save()
				pat = Patient.objects.get(user=request.user)
				doc = Doctor.objects.get(user = pat.doctor.user)
				notif = Notifications.objects.create(patient= pat, doctor= doc, hasNotification= True, msg= model_obj.report_content)

				return HttpResponseRedirect(reverse('mainapp:dashboard'))
		else:
			return HttpResponseRedirect(reverse('mainapp:loginuser'))

predict/templates/predict/index.html
{% load static %}

<!DOCTYPE html>
<html >
<!--From https://codepen.io/frytyler/pen/EGdtg-->
<head>
  <meta charset="UTF-8">
  <title>ML PREDICTER</title>
  <link href='https://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Arimo' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Hind:300' rel='stylesheet' type='text/css'>
<link href='https://fonts.googleapis.com/css?family=Open+Sans+Condensed:300' rel='stylesheet' type='text/css'>
<link rel="stylesheet" href="{% static 'predict/style.css' %}">
  
</head>

<body>
 <div class="login">

  <div class="sidenav">
      <img style="height:200px;width:200px;" src="{% static 'mainapp/logo.png' %}">

  <!-- <a href="{% url 'mainapp:account' %}">Profile</a> -->
  <a href="{% url 'predict:predicter' %}">Self Diagnosis Check</a>
  <!-- <a href="{% url 'mainapp:report' %}">View Reports</a> -->
      <a href="{% url 'mainapp:mail' %}">Send Email</a>
      <!-- <a href="{% url 'mainapp:updateuser' %}">Update Details</a> -->
      <a href="{% url 'mainapp:logout' %}">Logout</a>
  </div>
  
	<h1>Cardiovascular Disease Predictior</h1>

     <!-- Main Input For Receiving Query to our ML -->
    <form action="{% url 'predict:predicter' %}"method="post">
      {% csrf_token %}
    <input type="number" name="age" placeholder="Age" required="required" />
    <input type="number" name="sex" placeholder="Sex(1/0)" required="required" />
		<input type="number" name="cp" placeholder="Chest Pain(0/1)" required="required" />
		<input type="number" name="trestbps" placeholder="Rest blood pressure" required="required" />
		<input type="number" name="chol" placeholder="Cholestrol" required="required" />
		<input type="number" name="fbs" placeholder="Fasting blood sugar" required="required" />
		<input type="number" name="restecg" placeholder="Rest ECG result" required="required" />
        <input type="number" name="thalach" placeholder="Maximum heart rate" required="required" />
		<input type="number" name="exang" placeholder="Exercise induced angina" required="required" />
		<input type="number" name="oldpeak" placeholder="ST depression induced by exercise relative to rest" step="any" required="required" />
        <input type="number" name="slope" placeholder="the slope of the peak exercise ST segment" required="required" />
		<input type="number" name="ca" placeholder="Number of major vessels (0-3) colored by flourosopy" required="required" />
		<input type="number" name="thal" placeholder="Minimum Heart Rate" required="required" />
		
        <button type="submit" class="btn btn-primary btn-block btn-large">Predict</button>
    </form>

   <br>
   <br>
   {{ prediction_text }}

 </div>


</body>
</html>

predict/templates/predict/results.html
<!doctype html>
{% load static %}
<html lang="en">
<head>
  <meta charset="utf-8">
    <link rel="stylesheet" href="{% static 'mainapp/login.css' %}">
    <style type="text/css">
      #dispalyval{
        height: 600px;
        width: 600px;
        overflow-y: scroll;
      }
      .dispalyval{
        font-size: 20px;
      }
    </style>
  <title>MedEasy</title>

</head>

<body class="align">

  <div class="sidenav">
      <img style="height:200px;width:200px;" src="{% static 'mainapp/logo.png' %}">

  <!-- <a href="{% url 'mainapp:account' %}">Profile</a> -->
  <a href="{% url 'predict:predicter' %}">Self Diagnosis Check</a>
  <!-- <a href="{% url 'mainapp:report' %}">View Reports</a> -->
      <a href="{% url 'mainapp:mail' %}">Send Email</a>
      <!-- <a href="{% url 'mainapp:updateuser' %}">Update Details</a> -->
      <a href="{% url 'mainapp:logout' %}">Logout</a>
  </div>

  <div id="dispalyval">
	{% for param,value in params.items %}
		<div>
			<p class="dispalyval"><span style="color: white">{{param}}</span> : <span style="color:lightgreen" id="{{param}}">{{value}}</span></p>
		</div>
	{% endfor %}
  </div>

    <p style="color:red;font-size: 30px;">{{ output }}</p>

        <form name="myform" action="{% url 'predict:saveresult' %}" method="post">
          {% csrf_token %}
        	<input type="hidden" value="{{params.age}}" name="age" />
        	<input type="hidden" value="{{params.sex}}" name="sex"/>
    		<input type="hidden" value="{{params.cp}}" name="cp" />
    		<input type="hidden" value="{{params.trestbps}}" name="trestbps"  />
    		<input type="hidden" value="{{params.chol}}" name="chol"  />
    		<input type="hidden" value="{{params.fbs}}" name="fbs"  />
    		<input type="hidden" value="{{params.restecg}}" name="restecg"  />
            <input type="hidden" value="{{params.thalach}}" name="thalach"  />
    		<input type="hidden" value="{{params.exang}}" name="exang"  />
    		<input type="hidden" value="{{params.oldpeak}}" name="oldpeak"  />
            <input type="hidden" value="{{params.slope}}" name="slope"  />
    		<input type="hidden" value="{{params.ca}}" name="ca"  />
    		<input type="hidden" value="{{params.thal}}" name="thal"  />
    		
            <button type="submit">Save</button>
        </form>


  </div>

  <svg xmlns="http://www.w3.org/2000/svg" class="icons"><symbol id="arrow-right" viewBox="0 0 1792 1792"><path d="M1600 960q0 54-37 91l-651 651q-39 37-91 37-51 0-90-37l-75-75q-38-38-38-91t38-91l293-293H245q-52 0-84.5-37.5T128 1024V896q0-53 32.5-90.5T245 768h704L656 474q-38-36-38-90t38-90l75-75q38-38 90-38 53 0 91 38l651 651q37 35 37 90z"/></symbol><symbol id="lock" viewBox="0 0 1792 1792"><path d="M640 768h512V576q0-106-75-181t-181-75-181 75-75 181v192zm832 96v576q0 40-28 68t-68 28H416q-40 0-68-28t-28-68V864q0-40 28-68t68-28h32V576q0-184 132-316t316-132 316 132 132 316v192h32q40 0 68 28t28 68z"/></symbol><symbol id="user" viewBox="0 0 1792 1792"><path d="M1600 1405q0 120-73 189.5t-194 69.5H459q-121 0-194-69.5T192 1405q0-53 3.5-103.5t14-109T236 1084t43-97.5 62-81 85.5-53.5T538 832q9 0 42 21.5t74.5 48 108 48T896 971t133.5-21.5 108-48 74.5-48 42-21.5q61 0 111.5 20t85.5 53.5 62 81 43 97.5 26.5 108.5 14 109 3.5 103.5zm-320-893q0 159-112.5 271.5T896 896 624.5 783.5 512 512t112.5-271.5T896 128t271.5 112.5T1280 512z"/></symbol></svg>

</body>

<script type="text/javascript">
  if (Number(document.getElementById("chol").innerHTML)>240){
    document.getElementById("chol").style.color="red";
  }
  else{
    document.getElementById("chol").style.color="lightgreen";
  }
  if(Number(document.getElementById("trestbps").innerHTML)>140){
    document.getElementById("trestbps").style.color="red";
  }
  else{
    document.getElementById("trestbps").style.color="lightgreen";
  }
  if(Number(document.getElementById("thalach").innerHTML)>120){
    document.getElementById("thalach").style.color="red";
  }
  else{
    document.getElementById("thalach").style.color="lightgreen";
  }
</script>

</html>